"""Document generation services for CyberSaathi.

Generates editable NCRP complaint drafts, bank dispute emails, evidence
timelines, RTI drafts, journalist digests, and infographic copy. The
documents are always clearly marked as drafts and never impersonate
official submission.
"""

from __future__ import annotations

import uuid
from datetime import datetime, timezone
from typing import Optional

from shared.constants import PUBLIC_AUTHORITIES

from app.models import (
    ClusterRecord,
    ComplaintRecord,
    DocumentKind,
    ExtractedFacts,
    GeneratedDocument,
    RecoveryBand,
)
from app.services.seed_loader import get_seed_store


def _now() -> datetime:
    return datetime.now(tz=timezone.utc)


def _new_id(prefix: str) -> str:
    return f"{prefix}-{uuid.uuid4().hex[:10]}"


def _format_date(value) -> str:
    if value is None or value == "":
        return "—"
    if isinstance(value, str):
        try:
            value = datetime.fromisoformat(value.replace("Z", "+00:00"))
        except ValueError:
            return value
    if value.tzinfo is None:
        value = value.replace(tzinfo=timezone.utc)
    return value.astimezone(timezone.utc).strftime("%d %b %Y, %H:%M UTC")


def _amount_text(amount: Optional[float], currency: str = "INR") -> str:
    if amount is None or amount == 0:
        return "Not specified"
    return f"{currency} {amount:,.2f}"


def _evidence_bullets(complaint: ComplaintRecord, facts: ExtractedFacts) -> list[str]:
    bullets: list[str] = []
    if facts.utr:
        bullets.append(f"UTR / transaction reference: {facts.utr}")
    if facts.upi_id:
        bullets.append(f"UPI ID of receiver: {facts.upi_id}")
    if facts.amount:
        bullets.append(f"Reported amount: INR {facts.amount:,.2f}")
    if facts.timestamp:
        bullets.append(f"Transaction time: {_format_date(facts.timestamp)}")
    if facts.bank:
        bullets.append(f"Sender's bank / wallet: {facts.bank}")
    if facts.payment_app:
        bullets.append(f"Payment app used: {facts.payment_app}")
    if facts.phone:
        bullets.append(f"Caller / sender phone: {facts.phone}")
    if facts.handle:
        bullets.append(f"Social handle: {facts.handle}")
    if facts.url:
        bullets.append(f"Related URL: {facts.url}")
    if not bullets:
        bullets.append("No extracted transaction details yet. Attach screenshots and SMS text.")
    return bullets


def generate_ncrp_draft(
    complaint: ComplaintRecord,
    facts: ExtractedFacts,
    *,
    helpline_reference: Optional[str] = None,
) -> GeneratedDocument:
    location = complaint.location
    location_line = f"{location.district}, {location.state}"
    if location.pincode:
        location_line += f" - {location.pincode}"
    steps_taken = ["Reported the incident to CyberSaathi."]
    if helpline_reference:
        steps_taken.append(f"Called 1930 helpline and obtained reference number: {helpline_reference}.")
    else:
        steps_taken.append("1930 helpline call is pending.")

    body = f"""DRAFT — NCRP Cyber Crime Complaint

Date: {_format_date(_now())}
Complaint ID: {complaint.id}

To,
The Nodal Officer,
Cyber Crime Coordination Centre.

Subject: Report of {complaint.fraud_type.replace('_', ' ').title()} against the undersigned.

Respected Sir/Madam,

I, the undersigned, am filing this complaint regarding an incident of {complaint.fraud_type.replace('_', ' ')} on {_format_date(complaint.incident_at)}. The fraudulent transaction / activity caused a loss of {_amount_text(complaint.amount, complaint.amount_currency)}.

Incident details:
- Incident date and time: {_format_date(complaint.incident_at)}
- Location of reporting: {location_line}
- Category of fraud: {complaint.fraud_type}
- Payment method used: {complaint.payment_method}
- Reported amount: {_amount_text(complaint.amount, complaint.amount_currency)}

Narrative:
{complaint.summary}

Extracted facts and evidence references:
{chr(10).join('- ' + b for b in _evidence_bullets(complaint, facts))}

Steps already taken:
{chr(10).join('- ' + s for s in steps_taken)}

I request the Cyber Crime Coordination Centre to register this complaint, initiate investigation, and coordinate with the relevant bank, payment app, and law enforcement agency. I am willing to provide any further evidence or statements as required.

Yours sincerely,
(Victim, name withheld for privacy)

---
This is a draft generated by CyberSaathi for the victim's review. It has NOT been submitted to NCRP. The victim should review, edit, and submit through the official NCRP portal (cybercrime.gov.in) or by visiting the nearest cyber crime police station.
"""
    return GeneratedDocument(
        id=_new_id("doc"),
        complaint_id=complaint.id,
        kind=DocumentKind.NCRP_DRAFT,
        title="NCRP Complaint Draft",
        editable_body=body.strip(),
        created_at=_now(),
        export_status="draft",
    )


def generate_bank_dispute_email(
    complaint: ComplaintRecord,
    facts: ExtractedFacts,
) -> GeneratedDocument:
    subject = f"Dispute and fraud hold request — transaction {_format_date(complaint.incident_at)}"
    body = f"""DRAFT — Email to Bank Nodal Officer

To: nodal.officer@{facts.bank or 'bank'}.in
Subject: {subject}

Respected Sir/Madam,

I am writing to report an unauthorised / fraudulent transaction from my account on {_format_date(complaint.incident_at)} for an amount of {_amount_text(complaint.amount, complaint.amount_currency)}.

Account holder name: [Your full name]
Account number: [Your account number]
Customer ID / User ID: [Your customer ID]

Details of the disputed transaction:
- Transaction date and time: {_format_date(complaint.incident_at)}
- Amount: {_amount_text(complaint.amount, complaint.amount_currency)}
- UTR / Reference number: {facts.utr or '[Pending]'}
- Beneficiary UPI ID: {facts.upi_id or '[Pending]'}
- Beneficiary bank / wallet: {facts.bank or '[Pending]'}
- Payment app used: {facts.payment_app or '[Pending]'}
- Sender phone: {facts.phone or '[Pending]'}

Brief description of how the fraud occurred:
{complaint.summary}

I request you to:
1. Place an immediate hold on the disputed amount pending investigation.
2. Initiate a formal dispute under the bank's fraud policy.
3. Share the transaction trail with the cyber crime cell if requested.
4. Issue a written response with the dispute reference number and the outcome of your investigation.

I have also filed a complaint with the 1930 helpline and NCRP (complaint ID: {complaint.id}). Please coordinate with them as required.

Yours sincerely,
[Your full name]
[Your registered mobile number]
[Your registered email]

---
This is a draft email generated by CyberSaathi. Please review, attach any screenshots of the transaction, and send it from the email address registered with the bank.
"""
    return GeneratedDocument(
        id=_new_id("doc"),
        complaint_id=complaint.id,
        kind=DocumentKind.BANK_DISPUTE,
        title="Bank Dispute Email",
        editable_body=body.strip(),
        created_at=_now(),
        export_status="draft",
    )


def generate_evidence_timeline(
    complaint: ComplaintRecord,
    facts: ExtractedFacts,
) -> GeneratedDocument:
    events = [
        ("Incident occurred", _format_date(complaint.incident_at), complaint.summary),
        ("Reported on CyberSaathi", _format_date(complaint.created_at), "First complaint draft saved."),
    ]
    if facts.utr:
        events.append(("Transaction reference captured", "—", f"UTR: {facts.utr}"))
    if facts.upi_id:
        events.append(("Receiver UPI ID captured", "—", f"UPI ID: {facts.upi_id}"))
    if facts.bank:
        events.append(("Bank identified", "—", facts.bank))
    if facts.payment_app:
        events.append(("Payment app identified", "—", facts.payment_app))
    rows = "\n".join(
        f"- {event} ({when})\n    {detail}".strip() for event, when, detail in events
    )
    body = f"""DRAFT — Evidence Timeline

Complaint ID: {complaint.id}
Generated: {_format_date(_now())}

{rows}

Notes:
- All sensitive values such as Aadhaar, PAN, full card numbers, OTPs, PINs, and passwords have been redacted.
- Export this timeline as PDF before sharing with the police or NCRP.
"""
    return GeneratedDocument(
        id=_new_id("doc"),
        complaint_id=complaint.id,
        kind=DocumentKind.EVIDENCE_TIMELINE,
        title="Evidence Timeline",
        editable_body=body.strip(),
        created_at=_now(),
        export_status="draft",
    )


def generate_checklist(
    complaint: ComplaintRecord,
    recovery: RecoveryBand,
) -> GeneratedDocument:
    body = f"""DRAFT — Recovery Workflow Checklist

Complaint ID: {complaint.id}
Incident reported: {_format_date(complaint.incident_at)}

Within 60 minutes (Golden Hour, if applicable):
- [ ] Call 1930 helpline and save the reference number.
- [ ] Ask the bank to place a hold on the debited amount.
- [ ] Do not pay any additional amount to the scammer.

Within 24 hours:
- [ ] File the NCRP complaint at cybercrime.gov.in with the same reference number.
- [ ] Email the bank nodal officer with the disputed transaction details.
- [ ] Preserve original SMS, screenshots, and chat logs.

Within 3 days:
- [ ] Follow up with the bank in writing (email) and request a dispute ID.
- [ ] If a financial fraud is part of a wider pattern, check the "Similar reports" panel and
      consider joining the accountability alert.

Within 7 days:
- [ ] Visit the cyber crime police station with the printed complaint and evidence timeline.
- [ ] If you do not receive a response, request an acknowledgment under section 154 CrPC.

Recovery outlook:
{recovery.label} (range: {recovery.low_pct}% - {recovery.high_pct}%).

Why we say this:
{recovery.explanation}

Factors used:
{chr(10).join('- ' + f for f in recovery.factors)}
"""
    return GeneratedDocument(
        id=_new_id("doc"),
        complaint_id=complaint.id,
        kind=DocumentKind.RECOVERY_CHECKLIST,
        title="Recovery Workflow Checklist",
        editable_body=body.strip(),
        created_at=_now(),
        export_status="draft",
    )


def generate_complaint_package(
    complaint: ComplaintRecord,
    facts: ExtractedFacts,
    *,
    helpline_reference: Optional[str] = None,
) -> list[GeneratedDocument]:
    """Generate the full set of editable documents for a complaint."""

    recovery = _recovery_for_complaint(complaint, facts)
    return [
        generate_ncrp_draft(complaint, facts, helpline_reference=helpline_reference),
        generate_bank_dispute_email(complaint, facts),
        generate_evidence_timeline(complaint, facts),
        generate_checklist(complaint, recovery),
    ]


def _recovery_for_complaint(complaint: ComplaintRecord, facts: ExtractedFacts) -> RecoveryBand:
    from app.services.recovery import recovery_band

    return recovery_band(
        fraud_type=complaint.fraud_type,
        incident_at=complaint.incident_at,
        amount=complaint.amount,
        payment_method=complaint.payment_method,
        is_financial=complaint.payment_method != "none",
    )


def generate_rti_draft(cluster: ClusterRecord) -> GeneratedDocument:
    authority = PUBLIC_AUTHORITIES.get(cluster.states[0] if cluster.states else "", "State Cyber Crime Bureau")
    body = f"""DRAFT — RTI Application

To,
The Public Information Officer,
{authority}
[Address line 1]
[City, State, PIN]

Subject: Request for information regarding action taken on cyber crime complaints in {", ".join(cluster.states)}.

Respected Sir/Madam,

Under the Right to Information Act, 2005, I request the following information from your office:

1. How many cyber crime complaints matching the pattern of {cluster.fraud_type.replace('_', ' ')} were registered in the districts of {", ".join(cluster.districts)} during the period {_format_date(cluster.first_report_at)} to {_format_date(cluster.latest_report_at)}?

2. How many of those complaints were converted into FIRs?

3. What is the current status of investigation, and how many remain pending beyond 30 days?

4. What coordination has been carried out with the relevant banks, payment apps, and the Indian Cyber Crime Coordination Centre (I4C)?

5. What measures are being taken to issue public awareness or advisories in the affected districts?

I am attaching the following anonymised cluster summary for reference:
- Cluster reference: {cluster.id}
- Pattern: {cluster.fraud_type}
- Total reports in seed data: {cluster.report_count}
- Total reported amount: INR {cluster.total_amount:,.2f}
- States: {", ".join(cluster.states)}
- Districts: {", ".join(cluster.districts)}
- Time range: {_format_date(cluster.first_report_at)} to {_format_date(cluster.latest_report_at)}

This application is being filed in the public interest to seek transparency on cyber crime response.

Yours sincerely,
[Applicant name]
[Address]
[Phone number]
[Email]

---
This is a draft RTI application generated by CyberSaathi. The applicant must review, sign, attach the prescribed fee, and submit it to the relevant Public Information Officer. CyberSaathi is a demo / educational system and does not submit RTI applications on the user's behalf.
"""
    return GeneratedDocument(
        id=_new_id("doc"),
        complaint_id=cluster.id,
        kind=DocumentKind.RTI_DRAFT,
        title=f"RTI Draft — {cluster.fraud_type} cluster",
        editable_body=body.strip(),
        created_at=_now(),
        export_status="draft",
    )


def generate_journalist_digest(
    cluster: ClusterRecord,
    *,
    sample_identifier_values: list[str],
) -> GeneratedDocument:
    body = f"""DRAFT — Journalist / Researcher Digest

Cluster: {cluster.id}
Pattern: {cluster.fraud_type.replace('_', ' ').title()}
Window: {_format_date(cluster.first_report_at)} — {_format_date(cluster.latest_report_at)}

At a glance:
- Total reports in seed data: {cluster.report_count}
- Total reported amount: INR {cluster.total_amount:,.2f}
- States: {", ".join(cluster.states)}
- Districts: {", ".join(cluster.districts)}

Why this pattern triggered:
{cluster.trigger_reason or "Recurring reports in multiple districts with shared identifiers."}

Common identifiers (anonymised, do not publish full values):
{chr(10).join('- ' + s for s in sample_identifier_values)}

Accountability alert:
{"This cluster has crossed the 50-report, 30-day unresolved threshold defined by CyberSaathi." if cluster.report_count >= 50 else "This cluster is below the accountability threshold but is being monitored."}

Suggested story angles:
- Local impact: a single scam pattern hurting {cluster.report_count} people in {", ".join(cluster.states[:3])}.
- Money trail: how UPI / wallet rails are used to move small amounts across districts.
- Accountability: how many FIRs have been registered, how many remain pending beyond 30 days.

Source note:
All numbers in this digest are from CyberSaathi's deterministic seed data set, intended for demo, training, and policy discussion. They are not an official statistic.
"""
    return GeneratedDocument(
        id=_new_id("doc"),
        complaint_id=cluster.id,
        kind=DocumentKind.JOURNALIST_DIGEST,
        title=f"Journalist Digest — {cluster.fraud_type} cluster",
        editable_body=body.strip(),
        created_at=_now(),
        export_status="draft",
    )


def generate_infographic_copy(cluster: ClusterRecord) -> GeneratedDocument:
    body = f"""DRAFT — Infographic Copy

Title: When 50+ reports share the same UPI ID
Subtitle: A {cluster.fraud_type.replace('_', ' ')} pattern across {", ".join(cluster.states[:3])}

Key tiles:
- {cluster.report_count} reports in {len(cluster.districts)} districts.
- INR {cluster.total_amount:,.0f} reported lost in the seed data.
- First report: {_format_date(cluster.first_report_at)}.
- Latest report: {_format_date(cluster.latest_report_at)}.

Pull quote:
"Reporting quickly is the single biggest lever victims have. The next lever is making sure that ignored patterns don't stay invisible." — CyberSaathi

Footer:
All numbers are from CyberSaathi's deterministic seed data set.
"""
    return GeneratedDocument(
        id=_new_id("doc"),
        complaint_id=cluster.id,
        kind=DocumentKind.INFOGRAPHIC_COPY,
        title=f"Infographic Copy — {cluster.fraud_type} cluster",
        editable_body=body.strip(),
        created_at=_now(),
        export_status="draft",
    )


def generate_victim_notification(cluster: ClusterRecord) -> GeneratedDocument:
    """Short notification a victim in the cluster could forward to themselves.

    No PII; we tell the user their report is part of an escalated cluster
    and point them at the journalist digest, RTI draft, and the official
    1930 helpline.
    """

    body = f"""DRAFT — Victim Notification

Your case is part of an escalated pattern.

CyberSaathi's accountability engine has identified {cluster.report_count} "
"unresolved {cluster.fraud_type.replace('_', ' ')} reports across "
"{len(cluster.districts)} districts in {', '.join(cluster.states)}. "
"Because the pattern has crossed the 50-report, 30-day threshold with no "
"FIR or resolution status, CyberSaathi has generated:

- A public accountability alert
- A journalist digest (cluster-level counts only)
- A pre-filled RTI draft addressed to the relevant state cyber cell
- A shareable infographic

You can:
1. Continue to file your NCRP complaint at cybercrime.gov.in.
2. Forward the journalist digest to a local reporter if you choose to.
3. Submit the RTI draft to the public information officer of the
   relevant state cyber cell.

You are not alone. The pattern is now visible.
"""
    return GeneratedDocument(
        id=_new_id("doc"),
        complaint_id=cluster.id,
        kind=DocumentKind.VICTIM_NOTIFICATION,
        title=f"Victim Notification — {cluster.fraud_type} cluster",
        editable_body=body.strip(),
        created_at=_now(),
        export_status="draft",
    )
